version: '3'
services:
  starknet:
    image: quay.io/apibara/starknet:1.1.0
    command: start --data=/data --rpc=http://host.docker.internal:9944
    ports:
      - "7171:7171"

  sink-postgres:
    image: quay.io/apibara/sink-postgres:0.1.0
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://db.yiohhxbpytufllkmplkm.supabase.co:5432/postgres?user=postgres&password=JqLRLedRW8AQ8IkW
    command: run /data/examples/postgres/starknet_to_postgres.js --stream-url http://starknet:7171
    volumes:
      - /Users/apoorvsadana/Documents/GitHub/dna/examples:/data/examples
    depends_on:
      - starknet

  getting-started:
    image: docker/getting-started
    ports:
      - "80:80"